# Generated by Django 4.1.3 on 2022-11-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0010_alter_tipodainfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.clienteste', verbose_name='Cliente')),
            ],
        ),
    ]
