# Generated by Django 4.1.3 on 2022-11-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_delete_tipodainfo'),
        ('operacional', '0002_login_delete_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='login',
            name='nr_contato',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nrº Contato'),
        ),
        migrations.CreateModel(
            name='RedeWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_contato', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nrº Contato')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('login', models.CharField(blank=True, max_length=60, null=True, verbose_name='Login')),
                ('senha', models.CharField(blank=True, max_length=60, null=True, verbose_name='Senha')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.clienteste', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Rede-Wifi',
                'verbose_name_plural': 'Rede-Wifi',
                'ordering': ['referencia'],
            },
        ),
    ]
