# Generated by Django 4.1.3 on 2022-11-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_delete_tipodainfo'),
        ('operacional', '0003_login_email_login_nr_contato_redewifi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redewifi',
            name='login',
        ),
        migrations.AddField(
            model_name='login',
            name='nome',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='redewifi',
            name='nome',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='redewifi',
            name='nome_rede',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Rede'),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email para Contato'),
        ),
        migrations.AlterField(
            model_name='login',
            name='nr_contato',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefone para Contato'),
        ),
        migrations.AlterField(
            model_name='redewifi',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email para Contato'),
        ),
        migrations.AlterField(
            model_name='redewifi',
            name='nr_contato',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='telefone para Contato'),
        ),
        migrations.CreateModel(
            name='ManutencaoClienteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome')),
                ('nr_contato', models.CharField(blank=True, max_length=60, null=True, verbose_name='telefone para Contato')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email para Contato')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.clienteste', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Manutenção Cliente Final',
                'verbose_name_plural': 'Manutenção Cliente Final',
                'ordering': ['referencia'],
            },
        ),
    ]
