# Generated by Django 4.1.3 on 2022-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_cliente_nome_alter_fornecedor_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=60, unique=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=60, unique=True, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=60, unique=True, verbose_name='Tipo de Informação'),
        ),
    ]
