# Generated by Django 4.1.3 on 2022-11-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ')),
                ('nome', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome')),
                ('nr_contato', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email')),
                ('validacao_contrato', models.CharField(blank=True, max_length=14, null=True, verbose_name='Validação de contrato')),
                ('validade_certificacao', models.DateField(blank=True, null=True, verbose_name='Validade de certificação')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categoria.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.tipo')),
            ],
            options={
                'verbose_name': 'Formulario Geral',
                'verbose_name_plural': 'Formulario Geral',
                'ordering': ['tipo'],
            },
        ),
    ]
