# Generated by Django 4.1.3 on 2022-11-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categoria.fornecedor'),
        ),
    ]
