# Generated by Django 4.1.3 on 2022-11-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.cliente'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.fornecedor'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nome',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nr_contato',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone'),
        ),
    ]
