# Generated by Django 4.1.3 on 2022-11-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('Formulario', '0002_alter_formulario_cliente_alter_formulario_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulario',
            new_name='Formularios',
        ),
    ]
