# Generated by Django 4.1.3 on 2022-11-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=15, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('tel_fixo', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone')),
                ('tel_celular', models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
