# Generated by Django 4.1.3 on 2022-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteste',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='clienteste',
            name='tel_celular',
        ),
        migrations.RemoveField(
            model_name='clienteste',
            name='tel_fixo',
        ),
        migrations.AlterField(
            model_name='clienteste',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='clienteste',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clienteste',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
    ]
