# Generated by Django 4.1.3 on 2022-11-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_clienteste_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteste',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='clienteste',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='clienteste',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
    ]
