# Generated by Django 4.1.3 on 2022-11-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_clienteste_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteste',
            name='cliente',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome'),
        ),
    ]
