# Generated by Django 4.1.3 on 2022-11-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clienteste_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteste',
            options={'ordering': ['cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
