# Generated by Django 4.1.3 on 2022-11-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_clienteste_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteste',
            options={'ordering': ['clientef'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='clienteste',
            old_name='cliente',
            new_name='clientef',
        ),
    ]
