# Generated by Django 4.1.3 on 2022-11-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_clienteste_nr_contato_clienteste_validacao_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteste',
            name='nr_contato',
            field=models.CharField(max_length=14, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='TipoDaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.clienteste')),
            ],
        ),
    ]
