# Generated by Django 4.1.3 on 2022-11-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_clienteste_descricao'),
        ('Clientes', '0007_alter_clienteste_nr_contato_tipodainfo'),
    ]

    operations = [
    ]
