# Generated by Django 4.1.3 on 2022-11-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_merge_20221103_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodainfo',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo da Informação', 'verbose_name_plural': 'Tipo das Informaçoẽs'},
        ),
        migrations.RemoveField(
            model_name='tipodainfo',
            name='login',
        ),
        migrations.AddField(
            model_name='tipodainfo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.clienteste', verbose_name='Tipo da informação'),
        ),
        migrations.AlterField(
            model_name='clienteste',
            name='validade_certificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Validade de certificação'),
        ),
        migrations.AlterField(
            model_name='tipodainfo',
            name='nome',
            field=models.CharField(max_length=60, null=True, verbose_name='Login'),
        ),
    ]
