# Generated by Django 4.1.3 on 2022-11-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_alter_tipodainfo_options_remove_tipodainfo_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodainfo',
            options={'ordering': ['categoria'], 'verbose_name': 'Tipo da Informação', 'verbose_name_plural': 'Tipo da Informação'},
        ),
    ]
