# Generated by Django 4.1.3 on 2022-11-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0010_alter_tipodainfo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDaInfo',
        ),
    ]
